Adjective_1 = input("Give me a Adjective")
Nationality_1 = input("Give me a Nationality")
Person_1 = input("Give me a Persons Name")
Noun_1 = input("Give me a Noun")
Adjective_2 = input("Give me another adjective")
Noun_2 = input("Give me another Noun")
Adjective_3 = input("Give me a adjective")
Adjective_4 = input("Give me a adjective")
Plural_Noun_1 = input("Give me a Plural Noun")
Noun_3 = input("Give me a Noun")
Number_1 = input("Give me a number")
Shape_1 = input("Give me a shape")
Food_1 = input("Give me a type of food")
Food_2 = input("Give me another type of food")
Number_2 = input("Give me a another number")

print("Pizza was invented by a %s  %s" % (Adjective_1, Nationality_1))
print("chef name %s" % Person_1)
print("To make pizza, you need to take a lump of %s, and make a thin, round %s %s." % (Noun_1, Adjective_2, Noun_2))
print("Then you cover it with %s sauce, %s cheese, and fresh chopped %s." % (Adjective_3, Adjective_4, Plural_Noun_1))
print("Next you have to bake it in a very hot %s." % Noun_3)
print("When its done cut it into %s %s." % (Number_1, Shape_1))
print("Some kids like %s pizza best, but my favorite is the %s pizza." % (Food_1, Food_2))
print("If I could, I would eat pizza %s times of day." % Number_2)
