Adjective_1 = input("Give me a Adjective")
Nationality_1 = input("Give me a Nationality")
Person_1 = input("Give me a Persons Name")
Noun_1 = input("Give me a Noun")
Adjective_2 = input("Give me another adjective")
Noun_2 = input("Give me another Noun")
Adjective_3 = input("Give me a adjective")
Adjective_4 = input("Give me a adjective")
Plural_Noun_1 = input("Give me a Plural Noun")
Number_1 = input("Give me a number")
Shape_1 = input("Give me a shape")
Food_1 = input("Give me a type of food")
Food_2 = input("Give me another type of food")
Number_2 = input("Give me a another number")

print("Pizza was invented by a %s  %s" % (Adjective_1, Nationality_1))
print()
