list_words = []
list_words.append(input("Give me a adjective"))
list_words.append(input("Give me another adjective"))
list_words.append(input("Give me a type of bird"))
list_words.append(input("Give me a room in a house"))
list_words.append(input("Give me a verb in the past tense"))
list_words.append(input("Give me a verb"))
list_words.append(input("Give me a relative name"))
list_words.append(input("Give me a noun"))
list_words.append(input("Give me a liquid"))
list_words.append(input("Give me a verb ending in -ing"))
list_words.append(input("Give me a part of the body plural"))
list_words.append(input("Give me a plural noun"))
list_words.append(input("Give me a verb ending in -ing"))
list_words.append(input("Give me a noun"))

print("It was a %s, cold November day." % (list_words[0]))
print("I woke up to the %s smell of %s roasting in the %s downstairs" % (list_words[1], list_words[2], list_words[3]))
print("I %s down the stairs to see I can help %s the dinner" % (list_words[4], list_words[5]))
print("My mom said, see if %s needs a fresh %s." % (list_words[6], list_words[7]))
print("So I carried a try of glasses full of %s into the %s room." % (list_words[8], list_words[9]))
print("When I got there, I couldn't believe my %s!" % (list_words[10]))
print("There were %s %s on the %s" % (list_words[11], list_words[12], list_words[13]))

